//------------------------------------------------------------------------
//  FILENAME:  a_lut.sv
//  DESIGNER:  Szymon Madej
//  PROJECT:   Quadratic Approximation Unit
//  DATE:      2025-03-22
//  PURPOSE:   Look Up Table for coefficient A.
//
// Generated by MATLAB 9.14 and HDL Coder 4.1
//------------------------------------------------------------------------
`include "quadra.vh"

module a_lut (
  input x1_fxd_t x1_fxd,
  output a_fxd_t a
);

  x1_fxd_t a_lut_k;
  a_fxd_t a_lut_2[0:127];

     assign a_lut_2[0] = 21'sh1A57D8;
   assign a_lut_2[1] = 21'sh1A85CD;
   assign a_lut_2[2] = 21'sh1AB520;
   assign a_lut_2[3] = 21'sh1AE5C5;
   assign a_lut_2[4] = 21'sh1B17B1;
   assign a_lut_2[5] = 21'sh1B4AD7;
   assign a_lut_2[6] = 21'sh1B7F2B;
   assign a_lut_2[7] = 21'sh1BB49E;
   assign a_lut_2[8] = 21'sh1BEB25;
   assign a_lut_2[9] = 21'sh1C22B1;
   assign a_lut_2[10] = 21'sh1C5B33;
   assign a_lut_2[11] = 21'sh1C94A0;
   assign a_lut_2[12] = 21'sh1CCEE6;
   assign a_lut_2[13] = 21'sh1D09FA;
   assign a_lut_2[14] = 21'sh1D45CA;
   assign a_lut_2[15] = 21'sh1D824A;
   assign a_lut_2[16] = 21'sh1DBF68;
   assign a_lut_2[17] = 21'sh1DFD17;
   assign a_lut_2[18] = 21'sh1E3B46;
   assign a_lut_2[19] = 21'sh1E79E7;
   assign a_lut_2[20] = 21'sh1EB8E9;
   assign a_lut_2[21] = 21'sh1EF83D;
   assign a_lut_2[22] = 21'sh1F37D3;
   assign a_lut_2[23] = 21'sh1F779B;
   assign a_lut_2[24] = 21'sh1FB785;
   assign a_lut_2[25] = 21'sh1FF781;
   assign a_lut_2[26] = 21'sh00377F;
   assign a_lut_2[27] = 21'sh007770;
   assign a_lut_2[28] = 21'sh00B742;
   assign a_lut_2[29] = 21'sh00F6E7;
   assign a_lut_2[30] = 21'sh01364E;
   assign a_lut_2[31] = 21'sh017567;
   assign a_lut_2[32] = 21'sh01B424;
   assign a_lut_2[33] = 21'sh01F273;
   assign a_lut_2[34] = 21'sh023045;
   assign a_lut_2[35] = 21'sh026D8B;
   assign a_lut_2[36] = 21'sh02AA36;
   assign a_lut_2[37] = 21'sh02E637;
   assign a_lut_2[38] = 21'sh03217E;
   assign a_lut_2[39] = 21'sh035BFC;
   assign a_lut_2[40] = 21'sh0395A4;
   assign a_lut_2[41] = 21'sh03CE66;
   assign a_lut_2[42] = 21'sh040635;
   assign a_lut_2[43] = 21'sh043D02;
   assign a_lut_2[44] = 21'sh0472C0;
   assign a_lut_2[45] = 21'sh04A761;
   assign a_lut_2[46] = 21'sh04DAD9;
   assign a_lut_2[47] = 21'sh050D19;
   assign a_lut_2[48] = 21'sh053E17;
   assign a_lut_2[49] = 21'sh056DC5;
   assign a_lut_2[50] = 21'sh059C17;
   assign a_lut_2[51] = 21'sh05C903;
   assign a_lut_2[52] = 21'sh05F47C;
   assign a_lut_2[53] = 21'sh061E78;
   assign a_lut_2[54] = 21'sh0646ED;
   assign a_lut_2[55] = 21'sh066DD0;
   assign a_lut_2[56] = 21'sh069317;
   assign a_lut_2[57] = 21'sh06B6BA;
   assign a_lut_2[58] = 21'sh06D8AF;
   assign a_lut_2[59] = 21'sh06F8EE;
   assign a_lut_2[60] = 21'sh07176F;
   assign a_lut_2[61] = 21'sh07342A;
   assign a_lut_2[62] = 21'sh074F18;
   assign a_lut_2[63] = 21'sh076833;
   assign a_lut_2[64] = 21'sh077F73;
   assign a_lut_2[65] = 21'sh0794D3;
   assign a_lut_2[66] = 21'sh07A84E;
   assign a_lut_2[67] = 21'sh07B9E0;
   assign a_lut_2[68] = 21'sh07C982;
   assign a_lut_2[69] = 21'sh07D733;
   assign a_lut_2[70] = 21'sh07E2EE;
   assign a_lut_2[71] = 21'sh07ECB0;
   assign a_lut_2[72] = 21'sh07F476;
   assign a_lut_2[73] = 21'sh07FA40;
   assign a_lut_2[74] = 21'sh07FE0C;
   assign a_lut_2[75] = 21'sh07FFD7;
   assign a_lut_2[76] = 21'sh07FFA3;
   assign a_lut_2[77] = 21'sh07FD6F;
   assign a_lut_2[78] = 21'sh07F93C;
   assign a_lut_2[79] = 21'sh07F30A;
   assign a_lut_2[80] = 21'sh07EADC;
   assign a_lut_2[81] = 21'sh07E0B3;
   assign a_lut_2[82] = 21'sh07D492;
   assign a_lut_2[83] = 21'sh07C67C;
   assign a_lut_2[84] = 21'sh07B674;
   assign a_lut_2[85] = 21'sh07A47F;
   assign a_lut_2[86] = 21'sh0790A0;
   assign a_lut_2[87] = 21'sh077ADE;
   assign a_lut_2[88] = 21'sh07633D;
   assign a_lut_2[89] = 21'sh0749C3;
   assign a_lut_2[90] = 21'sh072E76;
   assign a_lut_2[91] = 21'sh07115E;
   assign a_lut_2[92] = 21'sh06F282;
   assign a_lut_2[93] = 21'sh06D1E9;
   assign a_lut_2[94] = 21'sh06AF9C;
   assign a_lut_2[95] = 21'sh068BA3;
   assign a_lut_2[96] = 21'sh066607;
   assign a_lut_2[97] = 21'sh063ED1;
   assign a_lut_2[98] = 21'sh06160C;
   assign a_lut_2[99] = 21'sh05EBC1;
   assign a_lut_2[100] = 21'sh05BFFC;
   assign a_lut_2[101] = 21'sh0592C6;
   assign a_lut_2[102] = 21'sh05642C;
   assign a_lut_2[103] = 21'sh053439;
   assign a_lut_2[104] = 21'sh0502F8;
   assign a_lut_2[105] = 21'sh04D077;
   assign a_lut_2[106] = 21'sh049CC2;
   assign a_lut_2[107] = 21'sh0467E6;
   assign a_lut_2[108] = 21'sh0431F0;
   assign a_lut_2[109] = 21'sh03FAED;
   assign a_lut_2[110] = 21'sh03C2EC;
   assign a_lut_2[111] = 21'sh0389FA;
   assign a_lut_2[112] = 21'sh035025;
   assign a_lut_2[113] = 21'sh03157D;
   assign a_lut_2[114] = 21'sh02DA0F;
   assign a_lut_2[115] = 21'sh029DEA;
   assign a_lut_2[116] = 21'sh02611F;
   assign a_lut_2[117] = 21'sh0223BA;
   assign a_lut_2[118] = 21'sh01E5CD;
   assign a_lut_2[119] = 21'sh01A767;
   assign a_lut_2[120] = 21'sh016896;
   assign a_lut_2[121] = 21'sh01296C;
   assign a_lut_2[122] = 21'sh00E9F7;
   assign a_lut_2[123] = 21'sh00AA48;
   assign a_lut_2[124] = 21'sh006A6E;
   assign a_lut_2[125] = 21'sh002A79;
   assign a_lut_2[126] = 21'sh1FEA7A;
   assign a_lut_2[127] = 21'sh1FAA81;
  assign a_lut_k = (x1_fxd == 7'b0000000 ? 7'b0000000 :
              (x1_fxd == 7'b1111111 ? 7'b1111111 :
              x1_fxd));
  assign a = a_lut_2[a_lut_k];

endmodule  // A_LUT

