//------------------------------------------------------------------------
//  FILENAME:  b_lut.sv
//  DESIGNER:  Szymon Madej
//  PROJECT:   Quadratic Approximation Unit
//  DATE:      2025-03-22
//  PURPOSE:   Look Up Table for coefficient B.
//
// Generated by MATLAB 9.14 and HDL Coder 4.1
//------------------------------------------------------------------------
`include "quadra.vh"

module b_lut (
  input x1_fxd_t x1_fxd,
  output b_fxd_t b
);

  x1_fxd_t b_lut_k;
  b_fxd_t b_lut_1[0:127];


      assign b_lut_1[0] = 22'sh0B5060;
   assign b_lut_1[1] = 22'sh0BA978;
   assign b_lut_1[2] = 22'sh0BFFA0;
   assign b_lut_1[3] = 22'sh0C52CC;
   assign b_lut_1[4] = 22'sh0CA2E4;
   assign b_lut_1[5] = 22'sh0CEFD0;
   assign b_lut_1[6] = 22'sh0D3984;
   assign b_lut_1[7] = 22'sh0D7FE8;
   assign b_lut_1[8] = 22'sh0DC2EC;
   assign b_lut_1[9] = 22'sh0E027C;
   assign b_lut_1[10] = 22'sh0E3E90;
   assign b_lut_1[11] = 22'sh0E7714;
   assign b_lut_1[12] = 22'sh0EABF8;
   assign b_lut_1[13] = 22'sh0EDD34;
   assign b_lut_1[14] = 22'sh0F0AB4;
   assign b_lut_1[15] = 22'sh0F3474;
   assign b_lut_1[16] = 22'sh0F5A68;
   assign b_lut_1[17] = 22'sh0F7C88;
   assign b_lut_1[18] = 22'sh0F9AC4;
   assign b_lut_1[19] = 22'sh0FB51C;
   assign b_lut_1[20] = 22'sh0FCB84;
   assign b_lut_1[21] = 22'sh0FDDFC;
   assign b_lut_1[22] = 22'sh0FEC7C;
   assign b_lut_1[23] = 22'sh0FF700;
   assign b_lut_1[24] = 22'sh0FFD88;
   assign b_lut_1[25] = 22'sh100010;
   assign b_lut_1[26] = 22'sh0FFE98;
   assign b_lut_1[27] = 22'sh0FF920;
   assign b_lut_1[28] = 22'sh0FEFAC;
   assign b_lut_1[29] = 22'sh0FE238;
   assign b_lut_1[30] = 22'sh0FD0D0;
   assign b_lut_1[31] = 22'sh0FBB70;
   assign b_lut_1[32] = 22'sh0FA224;
   assign b_lut_1[33] = 22'sh0F84F0;
   assign b_lut_1[34] = 22'sh0F63D8;
   assign b_lut_1[35] = 22'sh0F3EE8;
   assign b_lut_1[36] = 22'sh0F1628;
   assign b_lut_1[37] = 22'sh0EE9A4;
   assign b_lut_1[38] = 22'sh0EB964;
   assign b_lut_1[39] = 22'sh0E8578;
   assign b_lut_1[40] = 22'sh0E4DE8;
   assign b_lut_1[41] = 22'sh0E12C8;
   assign b_lut_1[42] = 22'sh0DD420;
   assign b_lut_1[43] = 22'sh0D9204;
   assign b_lut_1[44] = 22'sh0D4C84;
   assign b_lut_1[45] = 22'sh0D03B4;
   assign b_lut_1[46] = 22'sh0CB7A0;
   assign b_lut_1[47] = 22'sh0C685C;
   assign b_lut_1[48] = 22'sh0C1600;
   assign b_lut_1[49] = 22'sh0BC0A0;
   assign b_lut_1[50] = 22'sh0B6850;
   assign b_lut_1[51] = 22'sh0B0D24;
   assign b_lut_1[52] = 22'sh0AAF34;
   assign b_lut_1[53] = 22'sh0A4E9C;
   assign b_lut_1[54] = 22'sh09EB6C;
   assign b_lut_1[55] = 22'sh0985C4;
   assign b_lut_1[56] = 22'sh091DBC;
   assign b_lut_1[57] = 22'sh08B368;
   assign b_lut_1[58] = 22'sh0846EC;
   assign b_lut_1[59] = 22'sh07D85C;
   assign b_lut_1[60] = 22'sh0767D4;
   assign b_lut_1[61] = 22'sh06F574;
   assign b_lut_1[62] = 22'sh068158;
   assign b_lut_1[63] = 22'sh060B9C;
   assign b_lut_1[64] = 22'sh059458;
   assign b_lut_1[65] = 22'sh051BB4;
   assign b_lut_1[66] = 22'sh04A1C8;
   assign b_lut_1[67] = 22'sh0426B4;
   assign b_lut_1[68] = 22'sh03AA94;
   assign b_lut_1[69] = 22'sh032D8C;
   assign b_lut_1[70] = 22'sh02AFB8;
   assign b_lut_1[71] = 22'sh023138;
   assign b_lut_1[72] = 22'sh01B22C;
   assign b_lut_1[73] = 22'sh0132B0;
   assign b_lut_1[74] = 22'sh00B2EC;
   assign b_lut_1[75] = 22'sh0032F8;
   assign b_lut_1[76] = 22'sh3FB2F8;
   assign b_lut_1[77] = 22'sh3F330C;
   assign b_lut_1[78] = 22'sh3EB354;
   assign b_lut_1[79] = 22'sh3E33F0;
   assign b_lut_1[80] = 22'sh3DB4FC;
   assign b_lut_1[81] = 22'sh3D369C;
   assign b_lut_1[82] = 22'sh3CB8F0;
   assign b_lut_1[83] = 22'sh3C3C14;
   assign b_lut_1[84] = 22'sh3BC028;
   assign b_lut_1[85] = 22'sh3B454C;
   assign b_lut_1[86] = 22'sh3ACBA0;
   assign b_lut_1[87] = 22'sh3A5340;
   assign b_lut_1[88] = 22'sh39DC4C;
   assign b_lut_1[89] = 22'sh3966E4;
   assign b_lut_1[90] = 22'sh38F31C;
   assign b_lut_1[91] = 22'sh38811C;
   assign b_lut_1[92] = 22'sh3810F8;
   assign b_lut_1[93] = 22'sh37A2D4;
   assign b_lut_1[94] = 22'sh3736C4;
   assign b_lut_1[95] = 22'sh36CCE8;
   assign b_lut_1[96] = 22'sh366558;
   assign b_lut_1[97] = 22'sh360030;
   assign b_lut_1[98] = 22'sh359D84;
   assign b_lut_1[99] = 22'sh353D74;
   assign b_lut_1[100] = 22'sh34E014;
   assign b_lut_1[101] = 22'sh34857C;
   assign b_lut_1[102] = 22'sh342DC0;
   assign b_lut_1[103] = 22'sh33D8FC;
   assign b_lut_1[104] = 22'sh338740;
   assign b_lut_1[105] = 22'sh3338A0;
   assign b_lut_1[106] = 22'sh32ED38;
   assign b_lut_1[107] = 22'sh32A510;
   assign b_lut_1[108] = 22'sh326040;
   assign b_lut_1[109] = 22'sh321ED4;
   assign b_lut_1[110] = 22'sh31E0E4;
   assign b_lut_1[111] = 22'sh31A67C;
   assign b_lut_1[112] = 22'sh316FA8;
   assign b_lut_1[113] = 22'sh313C7C;
   assign b_lut_1[114] = 22'sh310CFC;
   assign b_lut_1[115] = 22'sh30E13C;
   assign b_lut_1[116] = 22'sh30B944;
   assign b_lut_1[117] = 22'sh30951C;
   assign b_lut_1[118] = 22'sh3074D0;
   assign b_lut_1[119] = 22'sh305864;
   assign b_lut_1[120] = 22'sh303FE4;
   assign b_lut_1[121] = 22'sh302B54;
   assign b_lut_1[122] = 22'sh301AB8;
   assign b_lut_1[123] = 22'sh300E14;
   assign b_lut_1[124] = 22'sh300570;
   assign b_lut_1[125] = 22'sh3000C8;
   assign b_lut_1[126] = 22'sh300020;
   assign b_lut_1[127] = 22'sh300378;
  assign b_lut_k = (x1_fxd == 7'b0000000 ? 7'b0000000 :
              (x1_fxd == 7'b1111111 ? 7'b1111111 :
              x1_fxd));
  assign b = b_lut_1[b_lut_k];

endmodule  // B_LUT

