//------------------------------------------------------------------------
//  FILENAME:  c_lut.sv
//  DESIGNER:  Szymon Madej
//  PROJECT:   Quadratic Approximation Unit
//  DATE:      2025-03-22
//  PURPOSE:   Look Up Table for coefficient C.
//
// Generated by MATLAB 9.14 and HDL Coder 4.1
//------------------------------------------------------------------------
`include "quadra.vh"

module c_lut (
  input x1_fxd_t x1_fxd,
  output c_fxd_t c
);

  x1_fxd_t c_lut_k;
  c_fxd_t c_lut_1[0:127];


     assign c_lut_1[0] = 21'sh0B3980;
   assign c_lut_1[1] = 21'sh0ADD00;
   assign c_lut_1[2] = 21'sh0A7D80;
   assign c_lut_1[3] = 21'sh0A1B80;
   assign c_lut_1[4] = 21'sh09B780;
   assign c_lut_1[5] = 21'sh095080;
   assign c_lut_1[6] = 21'sh08E700;
   assign c_lut_1[7] = 21'sh087B80;
   assign c_lut_1[8] = 21'sh080E00;
   assign c_lut_1[9] = 21'sh079E80;
   assign c_lut_1[10] = 21'sh072D00;
   assign c_lut_1[11] = 21'sh06BA00;
   assign c_lut_1[12] = 21'sh064500;
   assign c_lut_1[13] = 21'sh05CE80;
   assign c_lut_1[14] = 21'sh055680;
   assign c_lut_1[15] = 21'sh04DD00;
   assign c_lut_1[16] = 21'sh046280;
   assign c_lut_1[17] = 21'sh03E700;
   assign c_lut_1[18] = 21'sh036A00;
   assign c_lut_1[19] = 21'sh02ED00;
   assign c_lut_1[20] = 21'sh026E80;
   assign c_lut_1[21] = 21'sh01F000;
   assign c_lut_1[22] = 21'sh017080;
   assign c_lut_1[23] = 21'sh00F100;
   assign c_lut_1[24] = 21'sh007100;
   assign c_lut_1[25] = 21'sh1FF100;
   assign c_lut_1[26] = 21'sh1F7100;
   assign c_lut_1[27] = 21'sh1EF100;
   assign c_lut_1[28] = 21'sh1E7180;
   assign c_lut_1[29] = 21'sh1DF280;
   assign c_lut_1[30] = 21'sh1D7400;
   assign c_lut_1[31] = 21'sh1CF600;
   assign c_lut_1[32] = 21'sh1C7880;
   assign c_lut_1[33] = 21'sh1BFC00;
   assign c_lut_1[34] = 21'sh1B8080;
   assign c_lut_1[35] = 21'sh1B0680;
   assign c_lut_1[36] = 21'sh1A8D80;
   assign c_lut_1[37] = 21'sh1A1600;
   assign c_lut_1[38] = 21'sh199F80;
   assign c_lut_1[39] = 21'sh192B00;
   assign c_lut_1[40] = 21'sh18B800;
   assign c_lut_1[41] = 21'sh184700;
   assign c_lut_1[42] = 21'sh17D800;
   assign c_lut_1[43] = 21'sh176B00;
   assign c_lut_1[44] = 21'sh170000;
   assign c_lut_1[45] = 21'sh169780;
   assign c_lut_1[46] = 21'sh163100;
   assign c_lut_1[47] = 21'sh15CD00;
   assign c_lut_1[48] = 21'sh156B80;
   assign c_lut_1[49] = 21'sh150D00;
   assign c_lut_1[50] = 21'sh14B100;
   assign c_lut_1[51] = 21'sh145800;
   assign c_lut_1[52] = 21'sh140200;
   assign c_lut_1[53] = 21'sh13AE80;
   assign c_lut_1[54] = 21'sh135E80;
   assign c_lut_1[55] = 21'sh131180;
   assign c_lut_1[56] = 21'sh12C780;
   assign c_lut_1[57] = 21'sh128180;
   assign c_lut_1[58] = 21'sh123E00;
   assign c_lut_1[59] = 21'sh11FE80;
   assign c_lut_1[60] = 21'sh11C280;
   assign c_lut_1[61] = 21'sh118A00;
   assign c_lut_1[62] = 21'sh115500;
   assign c_lut_1[63] = 21'sh112380;
   assign c_lut_1[64] = 21'sh10F600;
   assign c_lut_1[65] = 21'sh10CC80;
   assign c_lut_1[66] = 21'sh10A680;
   assign c_lut_1[67] = 21'sh108400;
   assign c_lut_1[68] = 21'sh106600;
   assign c_lut_1[69] = 21'sh104B80;
   assign c_lut_1[70] = 21'sh103500;
   assign c_lut_1[71] = 21'sh102280;
   assign c_lut_1[72] = 21'sh101400;
   assign c_lut_1[73] = 21'sh100900;
   assign c_lut_1[74] = 21'sh100280;
   assign c_lut_1[75] = 21'sh100000;
   assign c_lut_1[76] = 21'sh100180;
   assign c_lut_1[77] = 21'sh100700;
   assign c_lut_1[78] = 21'sh101080;
   assign c_lut_1[79] = 21'sh101D80;
   assign c_lut_1[80] = 21'sh102F00;
   assign c_lut_1[81] = 21'sh104480;
   assign c_lut_1[82] = 21'sh105D80;
   assign c_lut_1[83] = 21'sh107A80;
   assign c_lut_1[84] = 21'sh109B80;
   assign c_lut_1[85] = 21'sh10C080;
   assign c_lut_1[86] = 21'sh10E980;
   assign c_lut_1[87] = 21'sh111580;
   assign c_lut_1[88] = 21'sh114600;
   assign c_lut_1[89] = 21'sh117A00;
   assign c_lut_1[90] = 21'sh11B180;
   assign c_lut_1[91] = 21'sh11EC80;
   assign c_lut_1[92] = 21'sh122B00;
   assign c_lut_1[93] = 21'sh126D00;
   assign c_lut_1[94] = 21'sh12B280;
   assign c_lut_1[95] = 21'sh12FB00;
   assign c_lut_1[96] = 21'sh134780;
   assign c_lut_1[97] = 21'sh139680;
   assign c_lut_1[98] = 21'sh13E900;
   assign c_lut_1[99] = 21'sh143E00;
   assign c_lut_1[100] = 21'sh149680;
   assign c_lut_1[101] = 21'sh14F180;
   assign c_lut_1[102] = 21'sh154F80;
   assign c_lut_1[103] = 21'sh15B000;
   assign c_lut_1[104] = 21'sh161300;
   assign c_lut_1[105] = 21'sh167880;
   assign c_lut_1[106] = 21'sh16E080;
   assign c_lut_1[107] = 21'sh174B00;
   assign c_lut_1[108] = 21'sh17B780;
   assign c_lut_1[109] = 21'sh182600;
   assign c_lut_1[110] = 21'sh189680;
   assign c_lut_1[111] = 21'sh190900;
   assign c_lut_1[112] = 21'sh197D00;
   assign c_lut_1[113] = 21'sh19F280;
   assign c_lut_1[114] = 21'sh1A6A00;
   assign c_lut_1[115] = 21'sh1AE280;
   assign c_lut_1[116] = 21'sh1B5C80;
   assign c_lut_1[117] = 21'sh1BD780;
   assign c_lut_1[118] = 21'sh1C5380;
   assign c_lut_1[119] = 21'sh1CD080;
   assign c_lut_1[120] = 21'sh1D4E80;
   assign c_lut_1[121] = 21'sh1DCD00;
   assign c_lut_1[122] = 21'sh1E4C00;
   assign c_lut_1[123] = 21'sh1ECB80;
   assign c_lut_1[124] = 21'sh1F4B00;
   assign c_lut_1[125] = 21'sh1FCB00;
   assign c_lut_1[126] = 21'sh004B00;
   assign c_lut_1[127] = 21'sh00CB00;
  assign c_lut_k = (x1_fxd == 7'b0000000 ? 7'b0000000 :
              (x1_fxd == 7'b1111111 ? 7'b1111111 :
              x1_fxd));
  assign c = c_lut_1[c_lut_k];

endmodule  // C_LUT

