// -------------------------------------------------------------
// 
// File Name: /userworkqum/szymadej/Intel_task/simulink_test/hdl_generated/three_in_adder/three_in_adder/three_in_adder.v
// Created: 2025-03-21 02:26:11
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: three_in_adder
// Source Path: three_in_adder
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module three_in_adder
          (t0_fxd,
           t1_fxd,
           t2_fxd,
           s_fxd);


  input   signed [30:0] t0_fxd;  // sfix31_En27
  input   signed [30:0] t1_fxd;  // sfix31_En27
  input   signed [30:0] t2_fxd;  // sfix31_En27
  output  signed [28:0] s_fxd;  // sfix29_En27


  wire signed [31:0] three_in_adder_stage2_add_cast;  // sfix32_En27
  wire signed [31:0] three_in_adder_stage2_add_cast_1;  // sfix32_En27
  wire signed [31:0] three_in_adder_op_stage1;  // sfix32_En27
  wire signed [32:0] three_in_adder_stage3_add_cast;  // sfix33_En27
  wire signed [32:0] three_in_adder_stage3_add_cast_1;  // sfix33_En27
  wire signed [32:0] three_in_adder_stage3_add_temp;  // sfix33_En27
  wire signed [28:0] three_in_adder_out1;  // sfix29_En27


  assign three_in_adder_stage2_add_cast = {t0_fxd[30], t0_fxd};
  assign three_in_adder_stage2_add_cast_1 = {t1_fxd[30], t1_fxd};
  assign three_in_adder_op_stage1 = three_in_adder_stage2_add_cast + three_in_adder_stage2_add_cast_1;



  assign three_in_adder_stage3_add_cast = {three_in_adder_op_stage1[31], three_in_adder_op_stage1};
  assign three_in_adder_stage3_add_cast_1 = {{2{t2_fxd[30]}}, t2_fxd};
  assign three_in_adder_stage3_add_temp = three_in_adder_stage3_add_cast + three_in_adder_stage3_add_cast_1;
  assign three_in_adder_out1 = three_in_adder_stage3_add_temp[28:0];



  assign s_fxd = three_in_adder_out1;

endmodule  // three_in_adder

