// -------------------------------------------------------------
// 
// File Name: /userworkqum/szymadej/Intel_task/simulink_test/hdl_generated/squarer/squarer/squarer.v
// Created: 2025-03-21 02:02:19
// 
// Generated by MATLAB 9.14 and HDL Coder 4.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.2
// Target subsystem base rate: 0.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: squarer
// Source Path: squarer
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module squarer
          (in1,
           out1);


  input   [16:0] in1;  // ufix17_En23
  output  [25:0] out1;  // ufix26_En24


  wire [33:0] Squarer_mul_temp;  // ufix34_En46
  wire [25:0] Squarer_out1;  // ufix26_En24


  assign Squarer_mul_temp = in1 * in1;
  assign Squarer_out1 = {14'b0, Squarer_mul_temp[33:22]};



  assign out1 = Squarer_out1;

endmodule  // squarer

